parameters:
    dugun_sms_factory_class: Dugun\Bundle\SmsBundle\Sms\ProviderFactory

services:
    dugun_sms:
        class: '%dugun_sms_factory_class%'
        arguments: ['%dugun_sms%', '%kernel.environment%']
